"""create people tables

Revision ID: f8129533384f
Revises: 
Create Date: 2026-05-21 17:59:49.506206

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'f8129533384f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('people',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('role', sa.String(length=120), nullable=True),
    sa.Column('relationship', sa.Enum('direct_report', 'peer', 'manager', 'skip_level', 'stakeholder', 'other', name='relationship_type'), nullable=False),
    sa.Column('slack_id', sa.String(length=40), nullable=True),
    sa.Column('jira_account_id', sa.String(length=80), nullable=True),
    sa.Column('github_handle', sa.String(length=80), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_people_email'), 'people', ['email'], unique=True)
    op.create_index(op.f('ix_people_slack_id'), 'people', ['slack_id'], unique=False)
    op.create_table('person_drafts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('role', sa.String(length=120), nullable=True),
    sa.Column('relationship', sa.Enum('direct_report', 'peer', 'manager', 'skip_level', 'stakeholder', 'other', name='relationship_type'), nullable=False),
    sa.Column('slack_id', sa.String(length=40), nullable=True),
    sa.Column('jira_account_id', sa.String(length=80), nullable=True),
    sa.Column('github_handle', sa.String(length=80), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=40), nullable=False),
    sa.Column('proposed_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_person_drafts_email'), 'person_drafts', ['email'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_person_drafts_email'), table_name='person_drafts')
    op.drop_table('person_drafts')
    op.drop_index(op.f('ix_people_slack_id'), table_name='people')
    op.drop_index(op.f('ix_people_email'), table_name='people')
    op.drop_table('people')
    # ### end Alembic commands ###
